export const adTemplates = [
  {
    id: 1,
    images: [
      {
        id: 1,
        title: "Mockup Template",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image.jpg",
        users: 450,
        saves: 10,
        tags: ["Product Showcase", "Minimal", "Instagram"],
        link: "https://i.pinimg.com/736x/87/fc/fa/87fcfa11b5fd783809f4db53535d4203.jpg",
        category: "Product Showcase",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        id: 2,
        title: "Sneaker Showcase",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-1.jpg",
        users: 250,
        saves: 30,
        tags: ["Product Showcase", "Minimal", "Instagram"],
        link: "https://i.pinimg.com/736x/87/fc/fa/87fcfa11b5fd783809f4db53535d4203.jpg",
        category: "Product Showcase",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        id: 3,
        title: "Pouch Mockup",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-2.jpg",
        users: 350,
        saves: 40,
        tags: ["Product Showcase", "Minimal", "Instagram"],
        link: "https://i.pinimg.com/736x/87/fc/fa/87fcfa11b5fd783809f4db53535d4203.jpg",
        category: "Product Showcase",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
    ],
    createdBy: "Creative Os",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: 2,
    images: [
      {
        id: 4,
        title: "Decoration",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-3.jpg",
        users: 600,
        saves: 5,
        tags: ["Interior", "Exterior"],
        link: "https://i.pinimg.com/564x/95/11/66/951166887924851aa8f004fac8e846eb.jpg",
        category: "Testimonial",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        id: 5,
        title: "Smartwatch Mockup",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-4.jpg",
        users: 500,
        saves: 53,
        tags: ["Device", "Mockup", "Watch"],
        link: "https://i.pinimg.com/564x/95/11/66/951166887924851aa8f004fac8e846eb.jpg",
        category: "Testimonial",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        id: 6,
        title: "Sneakers",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-5.jpg",
        users: 300,
        saves: 5,
        tags: ["Fashion", "Men"],
        link: "https://i.pinimg.com/564x/95/11/66/951166887924851aa8f004fac8e846eb.jpg",
        category: "Testimonial",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
    ],

    createdBy: "User2",
    createdOn: new Date(),
    updatedOn: new Date(),
  },

  {
    id: 3,
    images: [
      {
        id: 7,
        title: "Pomage",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-6.jpg",
        users: 1200,
        saves: 25,
        tags: ["Sale", "Discount", "Women"],
        link: "https://i.pinimg.com/564x/30/fb/72/30fb72f57d6fd5c4788c6538e58094b3.jpg",
        category: "Collage",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        id: 8,
        title: "Stationary Mockup",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-7.jpg",
        users: 1300,
        saves: 15,
        tags: ["Sale", "Discount", "Eye-Catching"],
        link: "https://i.pinimg.com/564x/30/fb/72/30fb72f57d6fd5c4788c6538e58094b3.jpg",
        category: "Collage",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        id: 9,
        title: "Classic Lamp",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-8.jpg",
        users: 1500,
        saves: 205,
        tags: ["Sale", "Discount", "Eye-Catching"],
        link: "https://i.pinimg.com/564x/30/fb/72/30fb72f57d6fd5c4788c6538e58094b3.jpg",
        category: "Collage",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
    ],
    createdBy: "John Smith",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: 4,
    images: [
      {
        id: 10,
        title: "Elegant Product",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-9.jpg",
        users: 800,
        saves: 18,
        tags: ["Product", "Carousel", "Elegant"],
        link: "https://i.pinimg.com/564x/97/ee/96/97ee96c5aba09c0677f3cfb5f4ab6503.jpg",
        category: "Social Proof",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        id: 11,
        title: "Game Controller",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-10.jpg",
        users: 800,
        saves: 18,
        tags: ["Product", "Carousel", "Elegant"],
        link: "https://i.pinimg.com/564x/97/ee/96/97ee96c5aba09c0677f3cfb5f4ab6503.jpg",
        category: "Social Proof",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        id: 12,
        title: "Bag Design",
        image:
          "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-11.jpg",
        users: 800,
        saves: 18,
        tags: ["Product", "Carousel", "Elegant"],
        link: "https://i.pinimg.com/564x/97/ee/96/97ee96c5aba09c0677f3cfb5f4ab6503.jpg",
        category: "Social Proof",
        createdOn: new Date(),
        updatedOn: new Date(),
      },
    ],
    createdBy: "Marketing Team",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
];

export const adCategories = [
  {
    id: 1,
    categoryName: "Features & Benefits",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: 2,
    categoryName: "Testimonial",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: 3,
    categoryName: "Social Proof",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: 4,
    categoryName: "Collage",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: 5,
    categoryName: "Product Showcase",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: 6,
    categoryName: "Story Ads",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: 7,
    categoryName: "Promotions",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: 8,
    categoryName: "Web Design",
    createdOn: new Date(),
    updatedOn: new Date(),
  },
];
